GET http://localhost:3001/todos

### 

POST http://localhost:3001/todos/new
Content-Type: application/json

{
    "text": "Get the milk"
}

###

DELETE http://localhost:3001/todo/delete/63e581839b6699b14bce6c39

###

PUT http://localhost:3001/todo/complete/63e57d53c08e7592faaec4d7

